base: ghcr.io/vanilla-os/nvidia:main
name: Vanilla Nvidia Cuda
id: vanilla-nvidia
labels:
  maintainer: self-maintained
args:
  DEBIAN_FRONTEND: noninteractive

modules:
- name: init-setup
  type: shell
  commands:
  - lpkg --unlock
  - apt-get update

# Put your custom actions behind this comment

# - Download debs
- name: install-cuda-repo
  type: shell
  commands:
  - wget https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda-repo-debian11-11-8-local_11.8.0-520.61.05-1_amd64.deb -nv -P /deb-pkgs

# - Install Cuda - Alt
#- name: install-cuda-deps
#  type: apt
#  source:
#    packages:
#    - gcc
#- name: install-cuda
#  type: shell
#  commands:
#  - echo "Downloading CUDA..."
#  - wget https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_520.61.05_linux.run -nv
#  - echo "Installing CUDA..."
#  - sh cuda_11.8.0_520.61.05_linux.run
#  - cat /var/log/cuda-installer.log # DEBUG

# - Install debs
- name: install-debs
  type: includes
  includes:
    - modules/50-install-debs

# - Install CUDA
- name: install-cuda-repo
  type: shell
  commands:
  - echo "Deleting .deb files..."
  - rm -rf /deb-pkgs/cuda-repo-debian11-11-8-local_11.8.0-520.61.05-1_amd64.deb
  - echo "Installing CUDA..."
  - echo "Copying keyring"
  - cp /var/cuda-repo-debian11-11-8-local/cuda-*-keyring.gpg /usr/share/keyrings/
  - echo "Adding repository"
  - touch /etc/apt/sources.list.d/debian.list
  - echo "deb http://deb.debian.org/debian/ bookworm main contrib non-free-firmware" > /etc/apt/sources.list.d/debian.list
  - echo "Updating repositories"
  - apt-get update
  - echo "Cleaning..."
  - apt-get clean

- name: install-cuda-nsight-1
  type: shell
  commands:
  - apt install -y cuda-nsight-11-8
  - apt clean

- name: install-cuda-nsight-2
  type: shell
  commands:
  - apt install -y cuda-nsight-compute-11-8
  - apt clean

- name: install-cuda-nsight-3
  type: shell
  commands:
  - apt install -y cuda-nsight-systems-11-8
  - apt clean

- name: install-cuda-nsight-4
  type: shell
  commands:
  - apt install -y nsight-compute-2022.3.0
  - apt clean

- name: install-cuda-nsight-5
  type: shell
  commands:
  - apt install -y nsight-systems-2022.4.2
  - apt clean

- name: install-cuda-libcu-1
  type: shell
  commands:
  - apt install -y libcublas-11-8 libcublas-dev-11-8 libcufft-11-8 
  - apt clean

- name: install-cuda-libcu-2
  type: shell
  commands:
  - apt install -y libcufft-dev-11-8 libcufile-11-8
  - apt clean

- name: install-cuda-deps-0
  type: shell
  commands:
  - apt install -y cuda-tools-11-8 cuda-visual-tools-11-8 default-jre default-jre-headless gds-tools-11-8 java-common libatk-wrapper-java libatk-wrapper-java-jni
  - apt clean

- name: install-cuda-deps-1
  type: shell
  commands:
  - apt install -y ca-certificates-java cuda cuda-11-8 cuda-cccl-11-8 cuda-command-line-tools-11-8 cuda-compiler-11-8 cuda-cudart-11-8 cuda-cudart-dev-11-8 cuda-cuobjdump-11-8 cuda-cupti-11-8 cuda-cupti-dev-11-8 cuda-cuxxfilt-11-8 cuda-demo-suite-11-8 cuda-documentation-11-8 cuda-driver-dev-11-8 cuda-drivers cuda-drivers-520 cuda-gdb-11-8
  - apt clean

- name: install-cuda-deps-2
  type: shell
  commands:
  - apt install -y cuda-libraries-11-8 cuda-libraries-dev-11-8 cuda-memcheck-11-8 cuda-nvcc-11-8 cuda-nvdisasm-11-8 cuda-nvml-dev-11-8 cuda-nvprof-11-8 cuda-nvprune-11-8 cuda-nvrtc-11-8 cuda-nvrtc-dev-11-8 cuda-nvtx-11-8 cuda-nvvp-11-8 cuda-profiler-api-11-8 cuda-runtime-11-8 cuda-sanitizer-11-8
  - apt clean

- name: install-cuda-deps-3
  type: shell
  commands:
  - apt install -y cuda-toolkit-11-8 cuda-toolkit-11-8-config-common cuda-toolkit-11-config-common cuda-toolkit-config-common
  - apt clean

- name: install-cuda-deps-4
  type: shell
  commands:
  - apt install -y libcufile-dev-11-8 libcurand-11-8 libcurand-dev-11-8 libcusolver-11-8 libcusolver-dev-11-8 libcusparse-11-8 libcusparse-dev-11-8 libnpp-11-8 libnpp-dev-11-8 libnvidia-compiler libnvidia-fbc1 libnvidia-nvvm4 libnvidia-opticalflow1 libnvjpeg-11-8 libnvjpeg-dev-11-8 libnvoptix1
  - apt clean

- name: install-cuda-deps-5
  type: shell
  commands:
  - apt install -y libtinfo5 libxcb-xinerama0 libxcb-xinput0 libxnvctrl-dev libxnvctrl0 nvidia-cuda-mps nvidia-detect nvidia-libopencl1 nvidia-opencl-common nvidia-opencl-icd nvidia-xconfig openjdk-17-jre openjdk-17-jre-headless
  - apt clean

- name: install-cuda
  type: apt
  source:
    packages:
    - cuda

# - Set Image Name
- name: set-image-name
  type: includes
  includes:
    - modules/80-set-image-abroot-config

# - DELME
#- name: example-packages
#  type: apt
#  source:
#    packages:
#    - vim

#- name: example-commands
#  type: shell
#  commands:
#  - echo Example output

#- name: package-modules
#  type: includes
#  includes:
#    - modules/50-install-debs
#    - modules/80-set-image-abroot-config

# Put your custom actions before this comment

- name: cleanup
  type: shell
  commands:
  - apt-get autoremove -y
  - apt-get clean
  - lpkg --lock

- name: fsguard
  type: fsguard
  CustomFsGuard: false
  FsGuardLocation: "/usr/sbin/FsGuard"
  GenerateKey: true
  FilelistPaths: ["/usr/bin"]
  modules:
    - name: remove-prev-fsguard
      type: shell
      commands:
        - rm -rf /FsGuard 
        - rm -f ./minisign.pub ./minisign.key 
        - chmod +x /usr/sbin/init

- name: cleanup2
  type: shell
  commands:
    - rm -rf /tmp/*
    - rm -rf /var/tmp/*
    - rm -rf /sources
